#
# Module manifest for module 'WinFormPS'
#
# Generated by: Francois-Xavier Cat
#
# Generated on: 2016-03-22
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'WinFormPS.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = 'df3d1de7-37bd-4262-9e10-69a72bd0f8f0'

# Author of this module
Author = 'Francois-Xavier Cat'

# Company or vendor of this module
CompanyName = 'LazyWinAdmin.com'

# Copyright statement for this module
Copyright = '(c) 2016 Francois-Xavier Cat. All rights reserved. Licensed under The MIT License (MIT)'

# Description of the functionality provided by this module
Description = 'PowerShell module to interact with Windows Forms (WinForms) controls'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Load-DataGridView','Load-ListBox','Refresh-DataGridView','Add-WFDataGridViewColumn','Add-WFDataGridViewRow','Add-WFListViewItem','Add-WFRichTextBoxText','Clear-WFDataGridViewSelection','Clear-WFErrorProvider','Clear-WFListBox','Clear-WFRichTextBox','ConvertTo-WFDataTable','Disable-WFButton','Disable-WFRichTextBox','Disable-WFTabControl','Disable-WFTextBox','Enable-WFButton','Enable-WFRichTextBox','Enable-WFTabControl','Enable-WFTextBox','Find-WFDataGridViewValue','Get-WFCheckedListBoxItem','Get-WFComboboxItem','Get-WFForm','Get-WFListBoxItem','Get-WFListViewItem','Import-WFDataGridView','Import-WFListBox','New-WFBalloonNotification','New-WFInputBox','New-WFMessageBox','New-WFOpenFileDialog','New-WFOpenFolderDialog','New-WFSpeakerBeep','Remove-WFListBoxItem','Reset-WFDataGridViewFormat','Set-WFDataGridView','Set-WFDataGridViewFilter','Set-WFForm','Set-WFListViewColumn','Set-WFRichTextBox','Update-WFDataGridView'


# Cmdlets to export from this module
#CmdletsToExport = '*'

# Variables to export from this module
#VariablesToExport = '*'

# Aliases to export from this module
#AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{
        # Title of the module
        Title = 'WinFormPS'

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Winforms', 'GUI', 'WindowsForms')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/lazywinadmin/WinFormPS/blob/master/LICENSE.md'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/lazywinadmin/WinFormPS'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

